name: Auto Blog Post

on:
  schedule:
    - cron: "0 * * * *"  # Executa a cada hora
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  auto-post:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install loguru gspread google-auth google-api-python-client webdriver-manager selenium

      - name: ⚙️ Criar arquivo de credenciais temporário
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: 🌍 Executar script de postagem automática
        env:
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          BLOG_USER: ${{ secrets.BLOG_USER }}
          BLOG_PASS: ${{ secrets.BLOG_PASS }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
        run: |
          python auto_post.py

      - name: 📤 Upload dos logs como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auto_post_logs
          path: logs_auto_post.log
