name: Auto Blog Post

on:
  schedule:
    - cron: '0 * * * *'  # executa todo início de hora
  workflow_dispatch:       # permite rodar manualmente

jobs:
  auto-post:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      BLOG_USER: ${{ secrets.BLOG_USER }}
      BLOG_PASS: ${{ secrets.BLOG_PASS }}
      SHEET_NAME: ${{ secrets.SHEET_NAME }}

    steps:
      # 1️⃣ Checkout do código
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Instalar dependências
      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install loguru gspread google-auth google-api-python-client selenium webdriver-manager

      # 4️⃣ Criar pasta de logs
      - name: 📝 Preparar logs
        run: mkdir -p logs

      # 5️⃣ Rodar auto_post.py e salvar logs
      - name: 🌍 Executar auto_post
        run: |
          python auto_post.py 2>&1 | tee logs/auto_post.log

      # 6️⃣ Upload dos logs como artefato
      - name: 📤 Upload dos logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auto_post_logs
          path: logs/auto_post.log
